snd-soc-ak4490-objs := ak4490.o
snd-soc-isl98608-objs := isl98608.o
snd-soc-ak8157-objs := ak8157.o
obj-$(CONFIG_SND_SOC_AK4490)	+= snd-soc-ak4490.o
obj-$(CONFIG_SND_SOC_AK4490)	+= snd-soc-isl98608.o
obj-$(CONFIG_SND_SOC_AK4490)	+= snd-soc-ak8157.o
