#
# Makefile for the kernel USB device drivers.
#

# Object files in subdirectories

#obj-$(CONFIG_USB_FUSB301)	+= fusb301.o
#obj-$(CONFIG_USB_TUSB320)	+= tusb320.o
obj-$(CONFIG_USB_HD3SS3220)	+= hd3ss3220.o
obj-$(CONFIG_USB_PI5USB302)	+= pi5usb302.o
#obj-$(CONFIG_USB_PI5USB)	+= pi5usb.o
