obj-$(CONFIG_TOUCHSCREEN_GT1X) += gt1x.o 
obj-$(CONFIG_TOUCHSCREEN_GT1X) += gt1x_extents.o 
obj-$(CONFIG_TOUCHSCREEN_GT1X) += gt1x_generic.o 
obj-$(CONFIG_TOUCHSCREEN_GT1X) += gt1x_tools.o 
obj-$(CONFIG_TOUCHSCREEN_GT1X) += gt1x_update.o

